name: beta

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version
        id: version
        run: |
          export HUGO_VERSION=$(curl -sSL https://api.github.com/repos/gohugoio/hugo/tags | jq -r "[.[].name] | .[0] | sub(\"v\";\"\")")
          echo "HUGO_VERSION=${HUGO_VERSION}" >> $GITHUB_ENV
          echo "Version: ${HUGO_VERSION}"
          echo "GO_VERSION="1.20.5" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ secrets.AWS_ASSUME_ROLE }}"
          aws-region: "us-east-1"
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Setup Buildx Remote Docker
        id: buildx
        uses: truemark/aws-buildx-remote-docker-instance-action@v4
        with:
          security-group-id: "${{ vars.SECURITY_GROUP_ID }}"
          subnet-id: "${{ vars.SUBNET_ID }}"
          instance-profile: "${{ vars.INSTANCE_PROFILE }}"
          region: "us-east-2"
      - name: Build Alpine 3.17
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="alpine" \
            --build-arg OS_VERSION="3.17" \
            --build-arg HUGO_VERSION="${{ env.HUGO_VERSION }}" \
            --build-arg GO_VERSION="${{ env.GO_VERSION }}" \
            -f Dockerfile \
            -t truemark/hugo:beta-alpine-3.17 \
            -t truemark/hugo:beta \
            .
      - name: Copy beta to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/hugo:beta"
          dest-image: "docker://public.ecr.aws/truemark/hugo:beta"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Copy beta-alpine-3.17 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/hugo:beta-alpine-3.17"
          dest-image: "docker://public.ecr.aws/truemark/hugo:beta-alpine-3.17"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Ubuntu Jammy
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="ubuntu" \
            --build-arg OS_VERSION="jammy" \
            --build-arg HUGO_VERSION="${{ env.HUGO_VERSION }}" \
            --build-arg GO_VERSION="${{ env.GO_VERSION }}" \
            -f Dockerfile \
            -t truemark/hugo:beta-ubuntu-jammy \
            .
      - name: Copy beta-ubuntu-jammy to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/hugo:beta-ubuntu-jammy"
          dest-image: "docker://public.ecr.aws/truemark/hugo:beta-ubuntu-jammy"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Debian Bookworm
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="debian" \
            --build-arg OS_VERSION="bookworm-slim" \
            --build-arg HUGO_VERSION="${{ env.HUGO_VERSION }}" \
            --build-arg GO_VERSION="${{ env.GO_VERSION }}" \
            -f Dockerfile \
            -t truemark/hugo:beta-debian-bookworm \
            .
      - name: Copy beta-debian-bookworm to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/hugo:beta-debian-bookworm"
          dest-image: "docker://public.ecr.aws/truemark/hugo:beta-debian-bookworm"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
      - name: Build Amazon Linux 2023
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg OS_NAME="amazonlinux" \
            --build-arg OS_VERSION="2023" \
            --build-arg HUGO_VERSION="${{ env.HUGO_VERSION }}" \
            --build-arg GO_VERSION="${{ env.GO_VERSION }}" \
            -f Dockerfile \
            -t truemark/hugo:beta-amazonlinux-2023 \
            .
      - name: Copy beta-amazonlinux-2023 to ECR
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://truemark/hugo:beta-amazonlinux-2023"
          dest-image: "docker://public.ecr.aws/truemark/hugo:beta-amazonlinux-2023"
          src-username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          src-password: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
          dest-username: "${{ steps.ecr-login.outputs.docker_username_public_ecr_aws }}"
          dest-password: "${{ steps.ecr-login.outputs.docker_password_public_ecr_aws }}"
          multi-arch: "all"
